# Run during the 'gulp build' command
# Overrides these options in _config.yml
url: http://nekodiablo.com
# Hides your drafts and future posts
future: true
show_drafts: false
# Removes the upper limit for posts generated
limit_posts: 0
